### ISSUE TITLE
no docs for API ?

### ISSUE THREAD

**Issue by Phosphorus15** [fr0der1c/EveryClass-server#12]
there's a APIv1 contained in this repo, while no API doc could be found. Although we can figure it out by the source code, it is not that convenient & standardized

**Comment by fr0der1c** [comment]
Hi,
To use the API, you will need to apply for an API Key. What's more, The API is not ready for use at the moment. We are going to prepare a more powerful and stable API (of course, with documents) after we finish tasks that are more important.

If you want to use our API, please contact me at frederic#admirable.one so we could communicate about the details further.
